export const FooterColumn = () => {
  return (
    <div className="text-sm bg-no-repeat box-border caret-transparent flex basis-full flex-col justify-start leading-[21px] max-w-full px-5 md:text-base md:basis-[33.3333%] md:leading-6 md:max-w-[33.3333%]">
      <div className="text-sm bg-no-repeat box-border caret-transparent leading-[21px] w-full md:text-base md:leading-6">
        <div className="text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6">
          <div className="text-sm bg-no-repeat box-border caret-transparent clear-both leading-[0px] mb-10 md:text-base before:accent-auto before:bg-no-repeat before:box-border before:caret-transparent before:clear-both before:text-white before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[0px] before:list-outside before:list-disc before:pointer-events-auto before:text-left before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:inset-y-0 before:font-sanchez before:md:text-base after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[0px] after:list-outside after:list-disc after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-sanchez after:md:text-base"></div>
          <div className="text-sm bg-no-repeat box-border caret-transparent clear-both hidden leading-[0px] mb-[50px] md:text-base md:block before:accent-auto before:bg-no-repeat before:box-border before:caret-transparent before:clear-both before:text-white before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[0px] before:list-outside before:list-disc before:pointer-events-auto before:text-left before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:inset-y-0 before:font-sanchez before:md:text-base"></div>
          <header className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:table after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-disc after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
            <h4 className="relative text-xl font-bold bg-no-repeat box-border caret-transparent clear-both tracking-[-0.6px] leading-5 font-red_hat_display after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:table after:text-xl after:not-italic after:normal-nums after:font-bold after:tracking-[-0.6px] after:leading-5 after:list-outside after:list-disc after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-red_hat_display">
              <span className="relative bg-no-repeat box-border caret-transparent inline-block z-[1]">
                <span className="bg-no-repeat box-border caret-transparent block before:accent-auto before:bg-no-repeat before:box-border before:caret-transparent before:clear-both before:text-white before:table before:text-xl before:not-italic before:normal-nums before:font-bold before:tracking-[-0.6px] before:leading-[0px] before:list-outside before:list-disc before:pointer-events-auto before:text-left before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-red_hat_display after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:table after:text-xl after:not-italic after:normal-nums after:font-bold after:tracking-[-0.6px] after:leading-[0px] after:list-outside after:list-disc after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-red_hat_display">
                  Our Services
                </span>
              </span>
            </h4>
          </header>
          <div className="text-sm bg-no-repeat box-border caret-transparent clear-both leading-[0px] mb-5 md:text-base before:accent-auto before:bg-no-repeat before:box-border before:caret-transparent before:clear-both before:text-white before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[0px] before:list-outside before:list-disc before:pointer-events-auto before:text-left before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:inset-y-0 before:font-sanchez before:md:text-base"></div>
          <div className="text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6">
            <div className="text-sm bg-no-repeat box-border caret-transparent flex leading-[21px] md:text-base md:leading-6">
              <ul className="text-sm bg-no-repeat box-border caret-transparent leading-[21px] list-none pl-0 md:text-base md:leading-6">
                <li className="relative text-sm bg-no-repeat box-border caret-transparent block leading-[21px] pl-4 pb-[7.7px] md:text-base md:leading-6 md:pb-[8.8px] before:accent-auto before:bg-primary before:box-border before:caret-transparent before:text-white before:block before:float-left before:text-sm before:not-italic before:normal-nums before:font-normal before:h-1.5 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-none before:pointer-events-none before:text-left before:indent-[0px] before:normal-case before:visible before:w-1.5 before:-ml-4 before:mt-[9px] before:rounded-md before:border-separate before:font-sanchez before:md:text-base before:md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
                  <a
                    href="https://amwerk.bold-themes.com/berlin/about-us/team/"
                    className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-primary after:bottom-[-3px] after:box-border after:caret-transparent after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:h-0.5 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:normal-case after:origin-[100%_50%] after:visible after:w-5 after:border-separate after:left-0 after:font-sanchez after:md:text-base after:md:leading-6 hover:text-white/70 hover:border-white/70"
                  >
                    Amwerk people
                  </a>
                </li>
                <li className="relative text-sm bg-no-repeat box-border caret-transparent block leading-[21px] pl-4 pb-[7.7px] md:text-base md:leading-6 md:pb-[8.8px] before:accent-auto before:bg-primary before:box-border before:caret-transparent before:text-white before:block before:float-left before:text-sm before:not-italic before:normal-nums before:font-normal before:h-1.5 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-none before:pointer-events-none before:text-left before:indent-[0px] before:normal-case before:visible before:w-1.5 before:-ml-4 before:mt-[9px] before:rounded-md before:border-separate before:font-sanchez before:md:text-base before:md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
                  <a
                    href="https://amwerk.bold-themes.com/berlin/services/pricing/"
                    className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-primary after:bottom-[-3px] after:box-border after:caret-transparent after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:h-0.5 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:normal-case after:origin-[100%_50%] after:visible after:w-5 after:border-separate after:left-0 after:font-sanchez after:md:text-base after:md:leading-6 hover:text-white/70 hover:border-white/70"
                  >
                    Project pricing
                  </a>
                </li>
                <li className="relative text-sm bg-no-repeat box-border caret-transparent block leading-[21px] pl-4 pb-[7.7px] md:text-base md:leading-6 md:pb-[8.8px] before:accent-auto before:bg-primary before:box-border before:caret-transparent before:text-white before:block before:float-left before:text-sm before:not-italic before:normal-nums before:font-normal before:h-1.5 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-none before:pointer-events-none before:text-left before:indent-[0px] before:normal-case before:visible before:w-1.5 before:-ml-4 before:mt-[9px] before:rounded-md before:border-separate before:font-sanchez before:md:text-base before:md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
                  <a
                    href="https://amwerk.bold-themes.com/berlin/about-us/testimonials/"
                    className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-primary after:bottom-[-3px] after:box-border after:caret-transparent after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:h-0.5 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:normal-case after:origin-[100%_50%] after:visible after:w-5 after:border-separate after:left-0 after:font-sanchez after:md:text-base after:md:leading-6 hover:text-white/70 hover:border-white/70"
                  >
                    Client testimonials
                  </a>
                </li>
                <li className="relative text-sm bg-no-repeat box-border caret-transparent block leading-[21px] pl-4 pb-[7.7px] md:text-base md:leading-6 md:pb-[8.8px] before:accent-auto before:bg-primary before:box-border before:caret-transparent before:text-white before:block before:float-left before:text-sm before:not-italic before:normal-nums before:font-normal before:h-1.5 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-none before:pointer-events-none before:text-left before:indent-[0px] before:normal-case before:visible before:w-1.5 before:-ml-4 before:mt-[9px] before:rounded-md before:border-separate before:font-sanchez before:md:text-base before:md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
                  <a
                    href="https://amwerk.bold-themes.com/berlin/services/our-process/"
                    className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-primary after:bottom-[-3px] after:box-border after:caret-transparent after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:h-0.5 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:normal-case after:origin-[100%_50%] after:visible after:w-5 after:border-separate after:left-0 after:font-sanchez after:md:text-base after:md:leading-6 hover:text-white/70 hover:border-white/70"
                  >
                    Our philosophy and process
                  </a>
                </li>
                <li className="relative text-sm bg-no-repeat box-border caret-transparent block leading-[21px] pl-4 pb-[7.7px] md:text-base md:leading-6 md:pb-[8.8px] before:accent-auto before:bg-primary before:box-border before:caret-transparent before:text-white before:block before:float-left before:text-sm before:not-italic before:normal-nums before:font-normal before:h-1.5 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-none before:pointer-events-none before:text-left before:indent-[0px] before:normal-case before:visible before:w-1.5 before:-ml-4 before:mt-[9px] before:rounded-md before:border-separate before:font-sanchez before:md:text-base before:md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
                  <a
                    href="https://amwerk.bold-themes.com/berlin/services/cost-calculator/"
                    className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-primary after:bottom-[-3px] after:box-border after:caret-transparent after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:h-0.5 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:normal-case after:origin-[100%_50%] after:visible after:w-5 after:border-separate after:left-0 after:font-sanchez after:md:text-base after:md:leading-6 hover:text-white/70 hover:border-white/70"
                  >
                    Cost Calculator
                  </a>
                </li>
                <li className="relative text-sm bg-no-repeat box-border caret-transparent block leading-[21px] pl-4 pb-[7.7px] md:text-base md:leading-6 md:pb-[8.8px] before:accent-auto before:bg-primary before:box-border before:caret-transparent before:text-white before:block before:float-left before:text-sm before:not-italic before:normal-nums before:font-normal before:h-1.5 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-none before:pointer-events-none before:text-left before:indent-[0px] before:normal-case before:visible before:w-1.5 before:-ml-4 before:mt-[9px] before:rounded-md before:border-separate before:font-sanchez before:md:text-base before:md:leading-6 after:accent-auto after:bg-no-repeat after:box-border after:caret-transparent after:clear-both after:text-white after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:text-left after:indent-[0px] after:normal-case after:visible after:border-separate after:font-sanchez after:md:text-base after:md:leading-6">
                  <a
                    href="https://amwerk.bold-themes.com/berlin/about-us/location/"
                    className="relative text-sm bg-no-repeat box-border caret-transparent leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-primary after:bottom-[-3px] after:box-border after:caret-transparent after:text-white after:hidden after:text-sm after:not-italic after:normal-nums after:font-normal after:h-0.5 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-none after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:normal-case after:origin-[100%_50%] after:visible after:w-5 after:border-separate after:left-0 after:font-sanchez after:md:text-base after:md:leading-6 hover:text-white/70 hover:border-white/70"
                  >
                    Our locations
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className="text-sm bg-no-repeat box-border caret-transparent clear-both leading-[0px] mb-10 md:text-base before:accent-auto before:bg-no-repeat before:box-border before:caret-transparent before:clear-both before:text-white before:table before:text-sm before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[0px] before:list-outside before:list-disc before:pointer-events-auto before:text-left before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:inset-y-0 before:font-sanchez before:md:text-base"></div>
        </div>
      </div>
    </div>
  );
};

